sts_gaming_group_kafka:
  consumers:
    instances:
      App\Consumer\ExampleConsumer:
        brokers: [ '34.116.153.222:9092']
        decoder: StsGamingGroup\KafkaBundle\Decoder\JsonDecoder
        group_id: 'mw'
        topics: [ 'mw_test' ]
  producers:
    instances:
      App\Producer\ExampleProducer:
        brokers: [ '34.116.153.222:9092']
        producer_topic: 'mw_test'